FROM mcr.microsoft.com/devcontainers/rust:latest

# Set locale to prevent warnings
ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

# Set default shell to zsh (already installed in base image)
ENV SHELL=/bin/zsh
